[tool.poetry]
name = "parser"
version = "0.1.0"
description = "A supermarket receipt parser written in Python using tesseract OCR"
authors = ["Matthias Endler <matthias-endler@gmx.net>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.6"
pyyaml = "^5.3"
python-dateutil = "^2.8.1"
Pillow = "^7.2.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
black = {version = "^20.8b1", allow-prereleases = true}

[tool.poetry.scripts]
run = 'parser:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
